language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

#before_install:
# - chmod +x gradlew

script:
  - mvn clean package -DskipTests=true

notifications:
  email: false

env:
  global:
    - GH_REF=github.com/aooppo/graphql.git